install.packages("BiocManager", repos="https://cran.rstudio.com")
install.packages("tidyverse",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("devtools",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("ggpubr",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("vegan",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("DHARMa",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("furrr",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("VGAM",dependencies=TRUE, repos='http://cran.rstudio.com/')
install.packages("cds",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("gridExtra",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("pracma",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("DoE.base",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("AlgDesignm",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("factoextra",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("readxl",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("reshape2",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("data.table",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("dtw",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("optparse",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("pdist",dependencies=TRUE, repos='http://cran.rstudio.com/') 
install.packages("proxy",dependencies=TRUE, repos='http://cran.rstudio.com/') 


BiocManager::install(version="3.15", update=TRUE, ask=FALSE)

BiocManager::install(c('devtools', 'AnVIL'))
